project:
  type: website
  output-dir: docs


website:
  title: "My Teaching Site"
  page-footer:
    center: "Copyright 2025, Thanicha Chanchaidechachai"
    right:
      - icon: github
        href: https://github.com/

  navbar:
    pinned: true
    left:
      - text: "Home"
        href: index.qmd
      - text: "Courses"
        menu:
          - text: "Veterinary Epidemiology"
            href: Courses/vet_epi.qmd
          - text: "Introduction to R"
            href: Courses/intro_r.qmd
      - text: "Research"
        href: publication.qmd
      - text: "About"
        href: profile.qmd
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/thanicha-chanchaidechachai/
      - icon: github
        href: https://github.com/AnnThanicha
      - icon: envelope
        href: mailto:thanicha.c@outlook.co.th

  sidebar:
    - title: "Veterinary Epidemiology"
      style: "docked"
      background: light
      contents:
        - Courses/vet_epi.qmd
        - Courses/module1.qmd
        - Courses/module2.qmd
    - title: "Introduction to R"
      style: "docked"
      background: light
      contents:
        - Courses/intro_r.qmd
        - Courses/module1.qmd
        - Courses/module2.qmd


format:
  html:
    theme: united
    toc: true
    css: styles.css
    search: true
    
date: last-modified
editor: visual