project:
  type: website
  output-dir: docs


website:
  title: "My Teaching Site"
  page-footer:
    center: "Copyright 2025, Thanicha Chanchaidechachai"
    right:
      - icon: github
        href: https://github.com/
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Courses"
        menu:
          - text: "Veterinary Epidemiology"
            href: Courses/vet_epi.qmd
          - text: "Introduction to R"
            href: Courses/intro_r.qmd
      - text: "About"
        href: profile.qmd
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/thanicha-chanchaidechachai/
      - icon: github
        href: https://github.com/AnnThanicha
      - icon: envelope
        href: mailto:thanicha.c@outlook.co.th

format:
  html:
    theme: united
    toc: true
    css: styles.css
    search: true

editor: visual