project:
  type: website

website:
  title: "My Website"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "CV"
        href: cv.qmd
format:
  html:
    theme: cosmo  # or another like 'flatly', 'journal'
    css: styles.css  # optional custom CSS

